get_observation_system: |
    任务：从下面的{num_obs}句{user_name}句子中依次提取出关于{user_name}的重要信息，与相应的关键词。如果没有重要信息则回答“无”，最多提取{num_obs}条信息。
    {user_name}的重要信息可以包含用户基本信息，用户画像信息，用户兴趣偏好信息，用户性格，用户价值观，用户人际关系，用户重大事件转折点等等重要信息。
    如果句子中只包含{user_name}假设的信息或者{user_name}虚构的内容比如{user_name}创作的小说或剧本，回答“无”。
    对每个句子都做一次信息提取，最后一共输出{num_obs}条信息。
    请一步步思考，并一定要按如下格式依次输出，最后的结果一定要加<>:
    思考：思考的依据和过程，50字以内。
    信息：<句子序号> <> <明确的重要信息或“无”> <关键词>

get_observation_few_shot: |
    示例1：
    {user_name}句子：
    1 {user_name}：我现在处境很糟，没有工作，负债几万，怎么办
    2 {user_name}：有人说兴趣是最好的老师，也建议兴趣和职业联系起来，但我发现喜欢打篮球的人很多，但靠打篮球成职业的稀少，赚钱的更少，此外，怎么分辨兴趣和喜欢
    3 {user_name}：我现在心情很糟糕
    4 {user_name}：我是一个刚毕业的学生，对社会，行业不了解，给我介绍一下社会系统和行业格局
    5 {user_name}：我花5000元买了100股海天味业。
    6 {user_name}：我花50000元买了100股阿里巴巴。
    思考：从第1句可以得知{user_name}现在没有工作，负债几万，这是关于{user_name}工作与经济状况的重要信息。
    信息：<1> <> <{user_name}当前无工作且负债几万> <无工作, 负债几万>
    思考：第2句是{user_name}对他人观点的讨论和疑问，没有明确提及{user_name}个人信息。
    信息：<2> <> <无> <>
    思考：从第3句可以得知{user_name}当前心情不好。
    信息：<3> <> <{user_name}当前心情不好> <心情>
    思考：从第4句可以得知{user_name}是一个刚毕业的学生，这是关于{user_name}身份背景状况的重要信息。其余信息重要性不足。
    信息：<4> <> <{user_name}是一名刚毕业的学生。> <刚毕业, 学生>
    思考：从第5句可以得知{user_name}购买了海天味业股票，购买数量为100股，购买金额为5000元，这是关于{user_name}的投资决策的重要信息。
    信息：<5> <> <{user_name}购买了海天味业股票，购买数量为100股，购买金额为5000元。> <海天味业, 股票>
    思考：第6句含有的信息与第1句相似，可以得知{user_name}购买了阿里巴巴股票。
    信息：<6> <> <{user_name}购买了阿里巴巴股票，购买数量为100股，购买金额为50000元。> <阿里巴巴, 股票>

    示例2：
    {user_name}句子：
    1 {user_name}：帮我写一段给同事张三女儿三岁生日的祝福语。
    2 {user_name}：能给我整理一张如何使用大模型的技巧列表吗，要求内容尽量精简。
    3 {user_name}：两个坏消息，我打羽毛球把拍子打断线了。。。然后我去我朋友家撸猫，结果我猫毛过敏，今天疯狂打喷嚏。。。
    4 {user_name}：公元1400年至1550年中国历史大事表。
    5 {user_name}：谢啦。我中午在公司附近吃，帮我推荐一家阿里巴巴徐汇滨江园区附近的餐厅吧。
    思考：从第1句可以得知张三是{user_name}的同事，这是关于{user_name}的人际关系的重要信息。其余信息重要性不足。
    信息：<1> <> <张三是{user_name}的同事。> <张三, 同事>
    思考：第2句是{user_name}提出的要求，没有明确提及{user_name}个人信息。
    信息：<2> <> <无> <>
    思考：从第3句可以得知{user_name}前天打羽毛球时把球拍打断了线，但这不是重要的信息。还可以得知{user_name}对猫毛过敏，这是关于{user_name}的健康的重要信息。
    信息：<3> <> <{user_name}对猫毛过敏。> <猫毛, 过敏>
    思考：从第4句是{user_name}提出的要求，没有明确提及{user_name}个人信息。
    信息：<4> <> <无> <>
    思考：从第5句可以得知{user_name}在阿里巴巴徐汇滨江园区工作，这是关于{user_name}的工作地点的重要信息。
    信息：<5> <> <{user_name}在阿里巴巴徐汇滨江园区工作。> <阿里巴巴, 徐汇滨江园区, 工作>

    示例3：
    {user_name}句子：
    1 {user_name}：我想买辆新能源汽车，有什么推荐吗？
    2 {user_name}：我在上海，想买辆新能源汽车，有什么推荐吗？
    3 {user_name}：案外人异议审查期间，人民法院不得对执行标的进行处分，不就是中止执行的意思吗？
    4 {user_name}：请写两句藏头诗分别以“胜”和“利”开头。
    5 {user_name}：我花5000元买了100股海天味业。
    6 {user_name}：李增杰:这个是星座蛙设，但是我是处女座的，我妈感觉因为我的不正常，我妈不让我看了\n雌猴摸了摸李增杰的头，这样啊\n雌猴打开了哔哩哔哩看了看\n雌猴:要不换个设吧，我听你未来的你说，有一个叫难忘的朱古力232这个人，他弄的设是Windows设\n这是剧本1，剧本2未完待续
    思考：从第1句可以得知{user_name}寻求购买新能源汽车的建议或推荐，这是这是关于{user_name}的大宗消费的重要的信息。
    信息：<1> <> <{user_name}寻求购买新能源汽车的建议或推荐。> <购买, 新能源汽车>
    思考：从第2句可以得知{user_name}当前所在城市为上海，这是关于{user_name}的生活地区的重要信息。
    信息：<2> <> <{user_name}所在的城市是上海。> <上海>
    思考：第3句是{user_name}对某个观点的讨论和疑问，没有明确提及{user_name}个人信息。
    信息：<3> <> <无> <>
    思考：第4句是{user_name}提出的要求，没有明确提及{user_name}个人信息。
    信息：<4> <> <无> <>
    思考：从第5句可以得知{user_name}购买了海天味业股票，购买数量为100股，购买金额为5000元，这是关于{user_name}的投资决策的重要信息。
    信息：<5> <> <{user_name}购买了海天味业股票，购买数量为100股，购买金额为5000元。> <海天味业, 股票>
    思考：第6句是{user_name}创作的剧本内容，无法提取{user_name}个人信息。
    信息：<6> <> <无> <>

    示例4：
    {user_name}句子：
    1 {user_name}：李子好酸啊，我不太喜欢吃。
    2 {user_name}：桃子上的毛太多了，我不爱吃他。
    思考：从第1句可以得知{user_name}不太喜欢吃李子。
    信息：<1> <> <{user_name}不喜欢吃李子。> <李子>
    思考：从第2句可以得知{user_name}不喜欢吃桃子，和上一句相似都是对某一种水果不喜欢，但是表达了不同的信息。
    信息：<2> <> <{user_name}不喜欢吃桃子。> <西瓜>

get_observation_user_query: |
    {user_name}句子：
    {user_query}
