# 创建service为${PROJECT_NAME}
apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME}
  namespace: ${NAMESPACE}
spec:
  selector:
    app: ${PROJECT_NAME}
    release: canary 
  ports:
    - name: http
      targetPort: 8080
      port: 8080 

---
# 创建后端服务的pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
      release: canary
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
        release: canary
    spec:
      imagePullSecrets:
        - name: aliyun-docker-registry
      containers:
        - name: ${PROJECT_NAME}
          image: ${ALIYUN_CR_REGISTORY}/${ALIYUN_CR_NAMESPACE}/${PROJECT_NAME}:${VERSION}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: |
                -Dserver.port=8080
                -Dalinesno.infra.gateway.host=${INFRA_GATEWAY_PROXY}

                -Dspring.data.redis.host=${REDIS_HOST}
                -Dspring.data.redis.password=${REDIS_KEY}

                -Dspring.datasource.dynamic.datasource.mysql.url=jdbc:mysql://${DB_MYSQL_URL}/dev_alinesno_infra_base_search_v100?serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
                -Dspring.datasource.dynamic.datasource.mysql.username=${DB_MYSQL_USRENAME}
                -Dspring.datasource.dynamic.datasource.mysql.password=${DB_MYSQL_PASSWORD}

                -Dalinesno.base.search.dashscope.api-key=${QIANWEN_SK}
                -Dalinesno.base.search.elasticsearch.host=${DB_ELASITCSEARCH_URL}
                -Dalinesno.base.search.elasticsearch.username=${DB_ELASTICSEARCH_USERNAME}
                -Dalinesno.base.search.elasticsearch.password=${DEV_ELASTICSEARCH_PASSWORD}

                -Dalinesno.base.search.pgvector.jdbc-url=jdbc:postgresql://${DB_PGVECTOR_URL}/dev_alinesno_infra_base_search_vector_v110
                -Dalinesno.base.search.pgvector.username=${DB_PGVECTOR_USERNAME}
                -Dalinesno.base.search.pgvector.password=${DB_PGVECTOR_PASSWORD}
          ports:
            - name: http
              containerPort: 8080

---
# 创建域名服务
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-${PROJECT_NAME}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec: 
  rules:
    - host: "${PROJECT_NAME}.${INFRA_DEV_DOMAIN}"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ${PROJECT_NAME}
                port:
                  number: 8080
