server:
  port: 30111

# spring 配置
spring:
  application:
    name: alinesno-infra-base-search-boot
    id: 452226530000
  datasource.dynamic:
    primary: mysql
    datasource:
      mysql:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dev_alinesno_infra_base_search_v100?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: root
        password: adminer
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local
  devtools:
    restart:
      enabled: true

# sa-token配置
sa-token:
  token-name: Authorization
  host-path: http://alinesno-infra-base-identity-auth-application.beta.base.infra.linesno.com
  sso:
    auth-url: ${sa-token.host-path}/login
    is-http: true
    check-ticket-url: ${sa-token.host-path}/sso/checkTicket
    slo-url: ${sa-token.host-path}/sso/signout
    get-data-url: ${sa-token.host-path}/sso/getData
  sign:
    secret-key: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor

# alinesno配置
alinesno:
  security:
    # 排除路径
    excludes:
      - /sso/**
      - /logout
      - /api/base/search/**
      - /api/infra/base/search/**
      - /v1/api/infra/base/im/chat/displayImage/*
  infra:
    gateway:
      host: http://alinesno-infra-base-gateway-proxy-application.beta.base.infra.linesno.com
  base:
    search:
      document:
        max-segment-length: 2048
      dashscope:
        api-key: xxxxx
        rerank-model-name: xxxx
      elasticsearch:
        host: 192.168.101.18:9200
        username: elastic
        password: 123456
      pgvector:
        jdbc-url: jdbc:postgresql://192.168.101.18:5432/postgres
        username: postgres
        password: 123456

actable:
  table:
    auto: update
  model:
    pack: com.alinesno.infra.base.search.entity;
  database:
    type: mysql
  index:
    prefix: alinesno_base_search_idx_
  unique:

